### ISSUE TITLE
 Chroma getOrCreateCollection error: TypeError: Cannot read properties of undefined (reading 'data')

### ISSUE THREAD

**Issue by AuYuHui** [chroma-core/gpt4-pdf-chatbot-langchain-chroma#4]
langchain V0.0.96
chromadb V1.4.1

![image](https://github.com/chroma-core/gpt4-pdf-chatbot-langchain-chroma/assets/38815121/e9fbc0bd-92da-4456-9cd8-aca627d8734b)

**Comment by jeffchuber** [comment]
@AuYuHui can you try upgrading to the latest version of Chroma? `1.5.1`?

**Comment by AuYuHui** [comment]
> @AuYuHui can you try upgrading to the latest version of Chroma? `1.5.1`?

After the upgrade, i can

**Comment by jeffchuber** [comment]
it works now? great!
